### PR TITLE
Homepage svgs

### PR DESCRIPTION
**Pull request by DaveG77**
Currently have theme and tracks. Need to find new track images before merge and get a finalized schedule + sponsor list

### CODE REVIEW

**Comment by firminm** [comment]
Tracks 2 & 3 are using incorrect SVGs - whitesheet and bubble. Everything else looks once that gets changed.

**Comment by DaveG77** [comment]
that's cause of the svg bug within figma I believe.  I tried lots of stuff to try to get those to work but it looks like only a png will give the original images

**Review by firminm — APPROVED** [review]
LGTM we'll add the sponsor/apply buttons in person tomorrow.

**Comment by DaveG77** [comment]
just added them

**Pull request merged**
